#!/bin/bash
#author:kiran
#description:shell script for automation
script_location=$(pwd)
LOG=/tmp/roboshop.log

echo -e "\e[32m install nginx\e[0m"
yum install nginx -y &>>${LOG}
systemctl enable nginx &>>${LOG}
systemctl start nginx &>>${LOG}

echo -e "\e[33m remove old content\e[0m"
rm -rf /usr/share/nginx/html/* &>>${LOG}

echo -e "\e[32m Download Frontend content\e[0m"
curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${LOG}
cd /usr/share/nginx/html &>>${LOG}

echo -e "\e[31m unziping frontend contenet in html\e[0m"
unzip /tmp/frontend.zip &>>${LOG}

echo -e "\e[32m copying roboshop nginxfile\e[0m"
cp ${script_location}/files/nginxroboshop.conf /etc/nginx/default.d/roboshop.conf
systemctl restart  nginx &>>${LOG}